<a href="https://colab.research.google.com/github/BrianHwang/TensorFlowDeveloperCertificate/blob/main/youtube_00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# in this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

conl+cmd + M M

https://tuewithmorris.medium.com/google-colab-notebooks-keyboard-shortcuts-aa6a008fb91b

Dowm + shift + return : new code line

shift + return : run code

cmd + shift + space : information


More specfically, 
* Introudce to Tensors
* Geeting information from tensors
* manipulation tensors
* Tensors

## Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
# create tensors with ts.constant()
# https://www.tensorflow.org/api_docs/python/tf/constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of demensios of a tensor
scalar.ndim

0

In [7]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
# check the dimension of vector
vector.ndim

1

In [15]:
# create a maxtrix
matrix = tf.constant([
                      [10,7],[7,10]
                      ])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [27]:
matrix.ndim

2

In [29]:
#create another matrix 
another_matrix = tf.constant([[10.0,7.0],
                              [7.0,10.0],
                              [5.0,6.0]], dtype=tf.float16)

another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5.,  6.]], dtype=float16)>

In [31]:
another_matrix.ndim

2

In [35]:
# let's create tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [37]:
tensor.ndim

3

what we've created so far:
* scalar: a single number
* vecor: a number with direction (wind speend)
* Matric: a 2-dimensional array of number
* Tensor: n-dimention array of number

### tf.variable

In [46]:
a = tf.Variable([10,7])
b = tf.constant([10,7])
a,b

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [51]:
#let's try to change
a[0].assign(7)
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [53]:
b[0] = 7
b

TypeError: ignored